### PR TITLE
GH-24 Refactor to use constructor injection for KubernetesModuleDeployer

### PR DESCRIPTION
**Pull request by markpollack**
- Removed unused 'taskDeployer' which was same instance as for streams

### CODE REVIEW

**Comment by ericbottard** [comment]
Hmm, I believe a bean of that name is (or maybe **was** needed, prior to the starter split that Mark did) needed. At the very least, we don't want a local bean to be used without the user understanding what is happening. All other runtimes have used the same approach of returning the same instance / same class for tasks until now

**Comment by markpollack** [comment]
We don't support tasks yet anyway, so we can remove it.  Looks like there will be different modulelauncher impl for stream and task anyway, so if we can remove a bit of cruft, so much the better.   Btw, would task support be done via setting redeploy policy to never in the replication controller?

**Comment by ericbottard** [comment]
I'm always for removing cruft. What I'm saying is that it (used to?) crash when a bean named taskModuleDeployer was not available.

Will have to look into that redeploy policy thing, you may know more about kubernetes than I do now :)

**Comment by markpollack** [comment]
I'll double check.  The contextLoads test passes fwiw.

**Comment by ericbottard** [comment]
The admin application indeed doesn't start with this patch applied. The ctor injection bit is fine though, I'll fix on merge

**Comment by ericbottard** [comment]
Merged as 58b579f

**Pull request closed without merging**
