### PR TITLE
Correct incorrect file reference and broken deploy spec

### PR DESCRIPTION
**Pull request by madorb**

### CODE REVIEW

**Comment by madorb** [comment]
Attempted to deploy to Kubernetes on Docker and ran into some confusion in the documentation and a failure because true was not escaped as 'true'

**Comment by sabbyanandan** [comment]
@madorb: Thanks for catching that!

**Comment by ilayaperumalg** [comment]
LGTM, merging.

**Comment by ilayaperumalg** [comment]
Rebased and merged as 9d7f720. @madorb Thank you again for fixing this.

**Pull request closed without merging**
